version: '3'
volumes:
  postgres_data: {}

services:
  bootpay_js_dev:
    image: docker.bootpay.co.kr/bootpay/bootpay-js:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/
    ports:
      - "10011:3001"
    hostname: bootpay-js-v1
    container_name: bootpay-js-v1
    extra_hosts:
      "test-database": 10.0.100.2